-- Give the shop owner the admin role.
--
-- APPLIED TO PRODUCTION 2026-08-19 via MCP, at the owner's explicit request.
--
-- user_roles was EMPTY. requireAdmin() in admin-authz.server.ts gates every
-- admin server function on a row in it, so /admin, order management, review
-- moderation, the CRM and the campaign screens rejected everyone — the owner
-- included. 23 RLS policies gate on the same has_role() check, so even at the
-- database level the shop's own orders and customers were invisible to them.
--
-- Keyed by EMAIL rather than a pasted uuid: the uuid is generated by auth and
-- differs per environment, so a hardcoded one would silently insert nothing
-- anywhere but this database — or, worse, match the wrong person.
--
-- Deliberately grants ONE account. Admin carries full read access to every
-- order, every customer's name, address and phone, and write access to the whole
-- catalogue — so it goes to the owner's account only, never handed out broadly.
-- Add another the same way, one row at a time, and only on request.
--
-- Idempotent: the NOT EXISTS guard makes a re-run a no-op.
--
-- VERIFIED AFTER APPLY by replaying the reads under this account's own JWT:
-- 4,672 products (all of them, including the 24 inactive), 1 order, 3 order
-- items, 5 profiles, 1 abandoned cart, 5 articles.
insert into public.user_roles (user_id, role)
select u.id, 'admin'::public.app_role
  from auth.users u
 where u.email = 'nitukbeclick@gmail.com'
   and not exists (
     select 1 from public.user_roles r
      where r.user_id = u.id and r.role = 'admin'::public.app_role
   );
